---
services:
  gnucash:
    build:
      context: .
    container_name: gnucash
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - NO_FULL=true
      - START_DOCKER=false
    ports:
      - 3000:3000
    restart: unless-stopped
    shm_size: 1gb
    volumes:
      - gnucash-config:/config
  db:
    image: postgres
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "su", "-c", "'pg_isready -d gnucash postgres'"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    shm_size: 256mb
    volumes:
      - gnucash-db:/var/lib/postgresql/data

volumes:
  gnucash-config:
  gnucash-db:
